"use client";
import type { Metadata } from "next";
import { web3onboard } from '@/lib/web3onboard';
import { Web3OnboardProvider } from '@web3-onboard/react';
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // FIXME: The specification of 'lang' has caused some hydration errors; should
  // it just be removed?
  return (
    <html lang="en-US">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Web3OnboardProvider web3Onboard={web3onboard}>
          {children}
        </Web3OnboardProvider>
      </body>
    </html>
  );
}
