#!/bin/bash

## Constants ##

RELEASE_HELP="usage: regen [-h | --help]
regenerate the 'full' desk (with dependencies) from the 'bare' desk

Flag arguments:
  -h, --help: show this help message"

## Helper Functions ##

## Arguments ##

while : ; do case ${1} in
	-h | --help) printf "%s\\n" "$RELEASE_HELP" && exit 1 ;;
	-*) printf "invalid option: %s\\n" "${1}" && exit 1 ;;
	*) break ;;
esac done

if [ "0" != "$#" ]; then
	printf "%s\\n" "$RELEASE_HELP" && exit 1
fi

## Processing ##

regen__basedir="$(dirname "$(dirname "$(dirname "$(readlink -f "$0")")")")"
regen__deskdir="${regen__basedir}/desk"

cd "${regen__deskdir}"
rm -rf full/
find bare -type f,l | while read f; do { d=$(dirname "$f" | sed "s/^bare/full/"); mkdir -p "$d"; ln -sr -t "$d" "$f"; }; done
mkdir -p full/app full/lib/ full/mar full/sur full/ted
ln -sr ../LICENSE.txt full/license.txt

git clone -b 411k --depth 1 https://github.com/urbit/urbit.git urb
cp urb/pkg/arvo/lib/verb* full/lib/
cp urb/pkg/arvo/sur/verb* full/sur/

git clone --depth 1 https://github.com/urbit/yard.git yar
cp yar/desk/lib/{dbug*,default-agent*,skeleton*,docket*} full/lib/
cp yar/desk/mar/{atom*,bill*,docket*,hoon*,json*,kelvin*,loob*,mime*,noun*,ship*,txt*,css*,png*,svg*,js*} full/mar/
cp yar/desk/sur/docket* full/sur/
